<a href="https://colab.research.google.com/github/YashitaaArya/Python-Practices/blob/main/HMD_KNNImputation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **HANDLING MISSING DATA**

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.impute import KNNImputer, SimpleImputer

In [2]:
df=pd.read_csv('train.csv')[['Age', 'Pclass', 'Fare', 'Survived']]

In [3]:
df.head()

    Age  Pclass     Fare  Survived
0  22.0       3   7.2500         0
1  38.0       1  71.2833         1
2  26.0       3   7.9250         1
3  35.0       1  53.1000         1
4  35.0       3   8.0500         0

In [4]:
df.isnull().mean()*100

Age         19.86532
Pclass       0.00000
Fare         0.00000
Survived     0.00000
dtype: float64

In [5]:
x=df.drop(columns=['Survived'])
y=df['Survived']

In [6]:
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=2)

In [8]:
x_train.head()

      Age  Pclass     Fare
30   40.0       1  27.7208
10    4.0       3  16.7000
873  47.0       3   9.0000
182   9.0       3  31.3875
876  20.0       3   9.8458

In [9]:
knn=KNNImputer()
x_train_trf=knn.fit_transform(x_train)
x_test_trf=knn.transform(x_test)

In [10]:
pd.DataFrame(x_train_trf, columns=x_train.columns)

      Age  Pclass      Fare
0    40.0     1.0   27.7208
1     4.0     3.0   16.7000
2    47.0     3.0    9.0000
3     9.0     3.0   31.3875
4    20.0     3.0    9.8458
..    ...     ...       ...
707  30.0     3.0    8.6625
708  24.2     3.0    8.7125
709  71.0     1.0   49.5042
710  28.0     1.0  221.7792
711  42.8     1.0   25.9250

[712 rows x 3 columns]

In [11]:
lr=LogisticRegression()
lr.fit(x_train_trf, y_train)
y_pred=lr.predict(x_test_trf)
accuracy_score(y_test, y_pred)

0.7039106145251397

In [14]:
for i in range(1,11):
  knn=KNNImputer(n_neighbors=i, weights='distance')
  x_train_trf=knn.fit_transform(x_train)
  x_test_trf=knn.transform(x_test)
  lr=LogisticRegression()
  lr.fit(x_train_trf, y_train)
  y_pred=lr.predict(x_test_trf)
  accuracy_score(y_test, y_pred)
  print("At ", i, "neighbours, Accuracy score is ", accuracy_score(y_test, y_pred))

At  1 neighbours, Accuracy score is  0.7206703910614525
At  2 neighbours, Accuracy score is  0.7094972067039106
At  3 neighbours, Accuracy score is  0.7039106145251397
At  4 neighbours, Accuracy score is  0.7039106145251397
At  5 neighbours, Accuracy score is  0.7039106145251397
At  6 neighbours, Accuracy score is  0.7039106145251397
At  7 neighbours, Accuracy score is  0.7039106145251397
At  8 neighbours, Accuracy score is  0.7039106145251397
At  9 neighbours, Accuracy score is  0.7039106145251397
At  10 neighbours, Accuracy score is  0.7039106145251397

Comparision with Simple Imputer --> mean

In [13]:
si=SimpleImputer()
x_train_trf2=si.fit_transform(x_train)
x_test_trf2=si.transform(x_test)
lr=LogisticRegression()
lr.fit(x_train_trf2, y_train)
y_pred2=lr.predict(x_test_trf2)
accuracy_score(y_test, y_pred2)

0.6927374301675978